name: dart
description: A simple StageXL web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: spencercornish <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0

dev_dependencies:
  build_runner: ^0.10.2
  built_value_generator: ^6.1.3
  build_web_compilers: ^0.4.3+1
  dart_dev: ^2.0.4
  dart_style: ^1.1.3
  sass: ^1.10.3
