version: 2.1
jobs:
    deploy:
        docker:
          - image: cimg/base:2020.01
        steps:
          - checkout
          - run: curl -sL https://firebase.tools | bash
          - run: firebase deploy --token=$FIREBASE_API_TOKEN

workflows:
  version: 2
  main_CI:
    jobs:
      - deploy:
          filters:
            branches:
              only: master